version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  commit-message:
      prefix: ":seedling:"
- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "weekly"
  allow:
    - dependency-name: "github.com/coredns/corefile-migration"
  commit-message:
    prefix: ":seedling:"
