/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/openshift/cluster-api/pkg/apis/machine/v1beta1"
	scheme "github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MachineControlPlaneSetsGetter has a method to return a MachineControlPlaneSetInterface.
// A group's client should implement this interface.
type MachineControlPlaneSetsGetter interface {
	MachineControlPlaneSets(namespace string) MachineControlPlaneSetInterface
}

// MachineControlPlaneSetInterface has methods to work with MachineControlPlaneSet resources.
type MachineControlPlaneSetInterface interface {
	Create(*v1beta1.MachineControlPlaneSet) (*v1beta1.MachineControlPlaneSet, error)
	Update(*v1beta1.MachineControlPlaneSet) (*v1beta1.MachineControlPlaneSet, error)
	UpdateStatus(*v1beta1.MachineControlPlaneSet) (*v1beta1.MachineControlPlaneSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.MachineControlPlaneSet, error)
	List(opts v1.ListOptions) (*v1beta1.MachineControlPlaneSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MachineControlPlaneSet, err error)
	MachineControlPlaneSetExpansion
}

// machineControlPlaneSets implements MachineControlPlaneSetInterface
type machineControlPlaneSets struct {
	client rest.Interface
	ns     string
}

// newMachineControlPlaneSets returns a MachineControlPlaneSets
func newMachineControlPlaneSets(c *MachineV1beta1Client, namespace string) *machineControlPlaneSets {
	return &machineControlPlaneSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineControlPlaneSet, and returns the corresponding machineControlPlaneSet object, and an error if there is any.
func (c *machineControlPlaneSets) Get(name string, options v1.GetOptions) (result *v1beta1.MachineControlPlaneSet, err error) {
	result = &v1beta1.MachineControlPlaneSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineControlPlaneSets that match those selectors.
func (c *machineControlPlaneSets) List(opts v1.ListOptions) (result *v1beta1.MachineControlPlaneSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MachineControlPlaneSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineControlPlaneSets.
func (c *machineControlPlaneSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a machineControlPlaneSet and creates it.  Returns the server's representation of the machineControlPlaneSet, and an error, if there is any.
func (c *machineControlPlaneSets) Create(machineControlPlaneSet *v1beta1.MachineControlPlaneSet) (result *v1beta1.MachineControlPlaneSet, err error) {
	result = &v1beta1.MachineControlPlaneSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		Body(machineControlPlaneSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineControlPlaneSet and updates it. Returns the server's representation of the machineControlPlaneSet, and an error, if there is any.
func (c *machineControlPlaneSets) Update(machineControlPlaneSet *v1beta1.MachineControlPlaneSet) (result *v1beta1.MachineControlPlaneSet, err error) {
	result = &v1beta1.MachineControlPlaneSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		Name(machineControlPlaneSet.Name).
		Body(machineControlPlaneSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *machineControlPlaneSets) UpdateStatus(machineControlPlaneSet *v1beta1.MachineControlPlaneSet) (result *v1beta1.MachineControlPlaneSet, err error) {
	result = &v1beta1.MachineControlPlaneSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		Name(machineControlPlaneSet.Name).
		SubResource("status").
		Body(machineControlPlaneSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineControlPlaneSet and deletes it. Returns an error if one occurs.
func (c *machineControlPlaneSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineControlPlaneSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineControlPlaneSet.
func (c *machineControlPlaneSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MachineControlPlaneSet, err error) {
	result = &v1beta1.MachineControlPlaneSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machinecontrolplanesets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
