/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/openshift/cluster-api/pkg/apis/machine/v1beta1"
	scheme "github.com/openshift/cluster-api/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MachineReplicaSetsGetter has a method to return a MachineReplicaSetInterface.
// A group's client should implement this interface.
type MachineReplicaSetsGetter interface {
	MachineReplicaSets(namespace string) MachineReplicaSetInterface
}

// MachineReplicaSetInterface has methods to work with MachineReplicaSet resources.
type MachineReplicaSetInterface interface {
	Create(*v1beta1.MachineReplicaSet) (*v1beta1.MachineReplicaSet, error)
	Update(*v1beta1.MachineReplicaSet) (*v1beta1.MachineReplicaSet, error)
	UpdateStatus(*v1beta1.MachineReplicaSet) (*v1beta1.MachineReplicaSet, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.MachineReplicaSet, error)
	List(opts v1.ListOptions) (*v1beta1.MachineReplicaSetList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MachineReplicaSet, err error)
	MachineReplicaSetExpansion
}

// machineReplicaSets implements MachineReplicaSetInterface
type machineReplicaSets struct {
	client rest.Interface
	ns     string
}

// newMachineReplicaSets returns a MachineReplicaSets
func newMachineReplicaSets(c *MachineV1beta1Client, namespace string) *machineReplicaSets {
	return &machineReplicaSets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineReplicaSet, and returns the corresponding machineReplicaSet object, and an error if there is any.
func (c *machineReplicaSets) Get(name string, options v1.GetOptions) (result *v1beta1.MachineReplicaSet, err error) {
	result = &v1beta1.MachineReplicaSet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinereplicasets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineReplicaSets that match those selectors.
func (c *machineReplicaSets) List(opts v1.ListOptions) (result *v1beta1.MachineReplicaSetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.MachineReplicaSetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinereplicasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineReplicaSets.
func (c *machineReplicaSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machinereplicasets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a machineReplicaSet and creates it.  Returns the server's representation of the machineReplicaSet, and an error, if there is any.
func (c *machineReplicaSets) Create(machineReplicaSet *v1beta1.MachineReplicaSet) (result *v1beta1.MachineReplicaSet, err error) {
	result = &v1beta1.MachineReplicaSet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machinereplicasets").
		Body(machineReplicaSet).
		Do().
		Into(result)
	return
}

// Update takes the representation of a machineReplicaSet and updates it. Returns the server's representation of the machineReplicaSet, and an error, if there is any.
func (c *machineReplicaSets) Update(machineReplicaSet *v1beta1.MachineReplicaSet) (result *v1beta1.MachineReplicaSet, err error) {
	result = &v1beta1.MachineReplicaSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinereplicasets").
		Name(machineReplicaSet.Name).
		Body(machineReplicaSet).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *machineReplicaSets) UpdateStatus(machineReplicaSet *v1beta1.MachineReplicaSet) (result *v1beta1.MachineReplicaSet, err error) {
	result = &v1beta1.MachineReplicaSet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinereplicasets").
		Name(machineReplicaSet.Name).
		SubResource("status").
		Body(machineReplicaSet).
		Do().
		Into(result)
	return
}

// Delete takes name of the machineReplicaSet and deletes it. Returns an error if one occurs.
func (c *machineReplicaSets) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinereplicasets").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineReplicaSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinereplicasets").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched machineReplicaSet.
func (c *machineReplicaSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MachineReplicaSet, err error) {
	result = &v1beta1.MachineReplicaSet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machinereplicasets").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
