/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/openshift/cluster-api/pkg/apis/machine/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineReplicaSets implements MachineReplicaSetInterface
type FakeMachineReplicaSets struct {
	Fake *FakeMachineV1beta1
	ns   string
}

var machinereplicasetsResource = schema.GroupVersionResource{Group: "machine.openshift.io", Version: "v1beta1", Resource: "machinereplicasets"}

var machinereplicasetsKind = schema.GroupVersionKind{Group: "machine.openshift.io", Version: "v1beta1", Kind: "MachineReplicaSet"}

// Get takes name of the machineReplicaSet, and returns the corresponding machineReplicaSet object, and an error if there is any.
func (c *FakeMachineReplicaSets) Get(name string, options v1.GetOptions) (result *v1beta1.MachineReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinereplicasetsResource, c.ns, name), &v1beta1.MachineReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineReplicaSet), err
}

// List takes label and field selectors, and returns the list of MachineReplicaSets that match those selectors.
func (c *FakeMachineReplicaSets) List(opts v1.ListOptions) (result *v1beta1.MachineReplicaSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinereplicasetsResource, machinereplicasetsKind, c.ns, opts), &v1beta1.MachineReplicaSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.MachineReplicaSetList{ListMeta: obj.(*v1beta1.MachineReplicaSetList).ListMeta}
	for _, item := range obj.(*v1beta1.MachineReplicaSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineReplicaSets.
func (c *FakeMachineReplicaSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinereplicasetsResource, c.ns, opts))

}

// Create takes the representation of a machineReplicaSet and creates it.  Returns the server's representation of the machineReplicaSet, and an error, if there is any.
func (c *FakeMachineReplicaSets) Create(machineReplicaSet *v1beta1.MachineReplicaSet) (result *v1beta1.MachineReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinereplicasetsResource, c.ns, machineReplicaSet), &v1beta1.MachineReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineReplicaSet), err
}

// Update takes the representation of a machineReplicaSet and updates it. Returns the server's representation of the machineReplicaSet, and an error, if there is any.
func (c *FakeMachineReplicaSets) Update(machineReplicaSet *v1beta1.MachineReplicaSet) (result *v1beta1.MachineReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinereplicasetsResource, c.ns, machineReplicaSet), &v1beta1.MachineReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineReplicaSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMachineReplicaSets) UpdateStatus(machineReplicaSet *v1beta1.MachineReplicaSet) (*v1beta1.MachineReplicaSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(machinereplicasetsResource, "status", c.ns, machineReplicaSet), &v1beta1.MachineReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineReplicaSet), err
}

// Delete takes name of the machineReplicaSet and deletes it. Returns an error if one occurs.
func (c *FakeMachineReplicaSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinereplicasetsResource, c.ns, name), &v1beta1.MachineReplicaSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineReplicaSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinereplicasetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.MachineReplicaSetList{})
	return err
}

// Patch applies the patch and returns the patched machineReplicaSet.
func (c *FakeMachineReplicaSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MachineReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinereplicasetsResource, c.ns, name, pt, data, subresources...), &v1beta1.MachineReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineReplicaSet), err
}
