/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/openshift/cluster-api/pkg/apis/machine/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineControlPlaneSets implements MachineControlPlaneSetInterface
type FakeMachineControlPlaneSets struct {
	Fake *FakeMachineV1beta1
	ns   string
}

var machinecontrolplanesetsResource = schema.GroupVersionResource{Group: "machine.openshift.io", Version: "v1beta1", Resource: "machinecontrolplanesets"}

var machinecontrolplanesetsKind = schema.GroupVersionKind{Group: "machine.openshift.io", Version: "v1beta1", Kind: "MachineControlPlaneSet"}

// Get takes name of the machineControlPlaneSet, and returns the corresponding machineControlPlaneSet object, and an error if there is any.
func (c *FakeMachineControlPlaneSets) Get(name string, options v1.GetOptions) (result *v1beta1.MachineControlPlaneSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinecontrolplanesetsResource, c.ns, name), &v1beta1.MachineControlPlaneSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineControlPlaneSet), err
}

// List takes label and field selectors, and returns the list of MachineControlPlaneSets that match those selectors.
func (c *FakeMachineControlPlaneSets) List(opts v1.ListOptions) (result *v1beta1.MachineControlPlaneSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinecontrolplanesetsResource, machinecontrolplanesetsKind, c.ns, opts), &v1beta1.MachineControlPlaneSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.MachineControlPlaneSetList{ListMeta: obj.(*v1beta1.MachineControlPlaneSetList).ListMeta}
	for _, item := range obj.(*v1beta1.MachineControlPlaneSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineControlPlaneSets.
func (c *FakeMachineControlPlaneSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinecontrolplanesetsResource, c.ns, opts))

}

// Create takes the representation of a machineControlPlaneSet and creates it.  Returns the server's representation of the machineControlPlaneSet, and an error, if there is any.
func (c *FakeMachineControlPlaneSets) Create(machineControlPlaneSet *v1beta1.MachineControlPlaneSet) (result *v1beta1.MachineControlPlaneSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinecontrolplanesetsResource, c.ns, machineControlPlaneSet), &v1beta1.MachineControlPlaneSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineControlPlaneSet), err
}

// Update takes the representation of a machineControlPlaneSet and updates it. Returns the server's representation of the machineControlPlaneSet, and an error, if there is any.
func (c *FakeMachineControlPlaneSets) Update(machineControlPlaneSet *v1beta1.MachineControlPlaneSet) (result *v1beta1.MachineControlPlaneSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinecontrolplanesetsResource, c.ns, machineControlPlaneSet), &v1beta1.MachineControlPlaneSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineControlPlaneSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMachineControlPlaneSets) UpdateStatus(machineControlPlaneSet *v1beta1.MachineControlPlaneSet) (*v1beta1.MachineControlPlaneSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(machinecontrolplanesetsResource, "status", c.ns, machineControlPlaneSet), &v1beta1.MachineControlPlaneSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineControlPlaneSet), err
}

// Delete takes name of the machineControlPlaneSet and deletes it. Returns an error if one occurs.
func (c *FakeMachineControlPlaneSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinecontrolplanesetsResource, c.ns, name), &v1beta1.MachineControlPlaneSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineControlPlaneSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinecontrolplanesetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.MachineControlPlaneSetList{})
	return err
}

// Patch applies the patch and returns the patched machineControlPlaneSet.
func (c *FakeMachineControlPlaneSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.MachineControlPlaneSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinecontrolplanesetsResource, c.ns, name, pt, data, subresources...), &v1beta1.MachineControlPlaneSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.MachineControlPlaneSet), err
}
