apiVersion: v1
kind: ConfigMap
metadata:
  name: rename-resources-config
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  renameResources: |
    rbac.authorization.k8s.io/ClusterRole/capi-manager-role=openshift-capi-manager-role
